api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 27017 }}
      transport: tcp
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
  template:
    volumes:
      - name: postdb-bigbadblogapphost-postdb-data
        storageType: AzureFile
        storageName: {{ .Env.SERVICE_POSTDB_VOLUME_BIGBADBLOGAPPHOST_POSTDB_DATA_NAME }} 
    containers:
      - image: {{ .Image }}
        name: postDb
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
        volumeMounts:
          - volumeName: postdb-bigbadblogapphost-postdb-data
            mountPath: /data/db
    scale:
      minReplicas: 1
tags:
  azd-service-name: postDb
  aspire-resource-name: postDb
